# Prometheus配置文件
global:
  scrape_interval: 15s
  evaluation_interval: 15s

# 规则文件
rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

# 抓取配置
scrape_configs:
  # Prometheus自身监控
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Flask应用监控
  - job_name: 'flask-app'
    static_configs:
      - targets: ['web:8000']
    metrics_path: '/metrics'
    scrape_interval: 10s
    scrape_timeout: 5s
    
  # 健康检查监控
  - job_name: 'flask-health'
    static_configs:
      - targets: ['web:8000']
    metrics_path: '/health'
    scrape_interval: 30s
    scrape_timeout: 5s

  # Nginx监控（如果启用了nginx-prometheus-exporter）
  # - job_name: 'nginx'
  #   static_configs:
  #     - targets: ['nginx-exporter:9113']

  # Redis监控（如果启用了redis-exporter）
  # - job_name: 'redis'
  #   static_configs:
  #     - targets: ['redis-exporter:9121']

  # Node Exporter监控（系统指标）
  # - job_name: 'node'
  #   static_configs:
  #     - targets: ['node-exporter:9100']

# 告警管理器配置
# alerting:
#   alertmanagers:
#     - static_configs:
#         - targets:
#           - alertmanager:9093